import path = require('path');
import { style } from './style';
import * as vscode from 'vscode';

const WORKSPACE = 'clippyReview';
const API_KEY = 'openAiApiKey';

const renderHtml = (msg: string, img: vscode.Uri) => `
  <style>
    ${style}
  </style>
  <body>
    <div class="message blurred">${msg}</div>
    <div class="pointer blurred"></div>
    <img src="${img}" />
  </body>
`;

export function activate(context: vscode.ExtensionContext) {
  let clippy: vscode.WebviewPanel | undefined = undefined;
  let disposable = vscode.commands.registerCommand('code-review-clippy.clippyReview', () => {
    if (!clippy) {
      clippy = vscode.window.createWebviewPanel("clippy", "Clippy", {
        viewColumn: vscode.ViewColumn.Beside,
        preserveFocus: true
      });
    }

    const imageUrl = vscode.Uri.file(
      path.join(context.extensionPath, "clippy.png")
    );

    const editor = vscode.window.activeTextEditor;
    let highlight;
    if (editor) {
      let cursorStart = editor.selection.start;
      let cursorEnd = editor.selection.end;
      const range: vscode.Range = new vscode.Range(cursorStart, cursorEnd);
      highlight = editor.document.getText(range);
    }

    const content = validateAndCreateContent(editor, highlight);
    const img = clippy.webview.asWebviewUri(imageUrl);
    clippy.webview.html = renderHtml(content, img);

    clippy.onDidDispose(
      () => {
        clippy = undefined;
      },
      null,
      context.subscriptions
    );
  });

  context.subscriptions.push(disposable);
}

const validateAndCreateContent = (editor: vscode.TextEditor | undefined, highlight: string | undefined): string => {
  const s = vscode.workspace.getConfiguration(WORKSPACE).get(API_KEY);
  if (s === null) {
    return toErrorMessage('No OpenAI API-key set!');
  }
  if (!editor) {
    return toErrorMessage('There\'s no active editors open.');
  }
  if (!highlight) {
    return toErrorMessage('There\'s no text on the editor!');
  }
  if (highlight.length > 1000) {
    return toErrorMessage('That\'s a long text, Clippy can\t read that much.');
  }
  return highlight;
};

const toErrorMessage = (errorMsg: string): string => {
  return `${generateErrorPrefix()}\n\n${errorMsg}`;
};

// These were generated by chatgpt, that's why they suck
const generateErrorPrefix = () => {
  const messages = [
    "Well, this is awkward. It seems like something went wrong. Let's pretend it didn't happen and start over, shall we?",
    "Oopsie daisy! Looks like there's a hiccup in the system. No worries, we'll have it fixed in a jiffy.",
    "Houston, we have a problem. But don't worry, we've got our finest scientists on the case to sort this out.",
    "Whoopsie, did we goof up? It's okay, we all make mistakes. Let's just learn from it and move forward.",
    "Oh dear, it seems like things are not going as planned. Don't worry, we'll get this sorted out and have you on your way in no time.",
    "That's not good.",
    "Clippy doesn\'t like this.",
  ];
  return messages[Math.floor(Math.random() * messages.length)];
};

export function deactivate() { }
